# Generated by Django 5.0.4 on 2024-05-11 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyUser',
        ),
    ]
