# Generated by Django 5.0.4 on 2024-05-11 19:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0006_alter_myuser_bio_alter_myuser_dob_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='doj',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
