# Generated by Django 5.0.4 on 2024-05-12 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0007_alter_myuser_doj'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='is_user',
            field=models.BooleanField(default=False),
        ),
    ]
