# Generated by Django 5.0.4 on 2024-05-12 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0010_alter_myuser_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='dob',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
