# Generated by Django 5.0.4 on 2024-05-18 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0013_forgotpassword'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Forgotpassword',
        ),
    ]
