# Generated by Django 5.0.4 on 2024-05-13 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DataBase', '0004_remove_music_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movies',
            name='description',
        ),
    ]
