# Generated by Django 5.0.4 on 2024-05-21 13:23

import DataBase.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataBase', '0006_movies_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='unique_id_movie',
            field=models.CharField(default=DataBase.models.unique_ids, max_length=10),
        ),
        migrations.AddField(
            model_name='music',
            name='unique_id_music',
            field=models.CharField(default=DataBase.models.unique_ids, max_length=10),
        ),
        migrations.AddField(
            model_name='photos',
            name='unique_id_photo',
            field=models.CharField(default=DataBase.models.unique_ids, max_length=10),
        ),
        migrations.AddField(
            model_name='videos',
            name='unique_id_video',
            field=models.CharField(default=DataBase.models.unique_ids, max_length=10),
        ),
        migrations.AlterField(
            model_name='movies',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='movies/'),
        ),
        migrations.AlterField(
            model_name='movies',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='dynamic/file/music/thumbnails'),
        ),
        migrations.AlterField(
            model_name='music',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='music/'),
        ),
        migrations.AlterField(
            model_name='music',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='music/thumbnails'),
        ),
        migrations.AlterField(
            model_name='photos',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='photos/'),
        ),
        migrations.AlterField(
            model_name='videos',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='videos/'),
        ),
    ]
